### ISSUE TITLE
Estudo - Docker/Dev Containers - Conceitos Básicos e Fundamentos

### ISSUE THREAD

**Issue by samuelncaetano** [unb-mds/2024-2-SuaFinanca#1]
### Descrição
Explorar conceitos essenciais do Docker para construção e gerenciamento de ambientes isolados, com foco em imagens e containers. Compreender o uso da extensão **Dev Containers** no VSCode para facilitar o desenvolvimento em containers Docker.

### Escopo da Tarefa
- [x] Estudar e criar uma imagem Docker personalizada com um Dockerfile.
- [x] Criar e gerenciar containers usando comandos básicos do Docker.
- [x] Configurar a comunicação entre containers, como backend e banco de dados.
- [x] Configurar um Dev Container para o projeto no VSCode.

### Técnicas e Ferramentas Necessárias
- Docker e Docker CLI
- Extensão Dev Containers para VSCode

**Comment by kalebmacedo** [comment]
Issue complited! The contests available on https://github.com/unb-mds/2024-2-Squad11/blob/main/documents/Resumo-Docker.md
