### ISSUE TITLE
Estudo - Testes Automatizados - Fundamentos e Práticas (Unitários, Integração, E2E)

### ISSUE THREAD

**Issue by samuelncaetano** [unb-mds/2024-2-SuaFinanca#2]
### Descrição
Explorar tipos de testes automatizados com foco em unitários e de integração, além de boas práticas para alcançar alta cobertura e garantir qualidade do sistema.

### Escopo da Tarefa
- [x] Conhecer os conceitos fundamentais de testes de software.
- [x] Compreender as diferenças entre testes unitários, integração e E2E.
- [x] Saber como aplicar boas práticas como nomes descritivos e isolamento dos testes.
- [x] Implementar design patterns de teste (AAA, Test Data Builder, Mock Objects).
- [x] Saber como configurar e usar ferramentas de testes, como Vitest, Jest, Supertest e Cypress.
- [x] Adotar práticas de teste (AAA, isolamento, nomes descritivos).

### Técnicas e Ferramentas Necessárias
- Bibliotecas: Vitest, Jest, Supertest e Cypress.

### Informações Adicionais
- Princípio “FIRST” nos testes automatizados

**Comment by LucasAlves71** [comment]
Issue completed!
The content is available on https://github.com/unb-mds/2024-2-Squad11/blob/main/documents/Resumo-Testes-Automatizados.md

**Comment by LucasAlves71** [comment]
Issue completed!
The content is available on https://github.com/unb-mds/2024-2-Squad11/blob/main/documents/Resumo-Testes-Automatizados.md
