### ISSUE TITLE
Estudo - Backend - Análise das tecnologias para o Backend

### ISSUE THREAD

**Issue by samuelncaetano** [unb-mds/2024-2-SuaFinanca#6]
### Descrição

Esta tarefa visa a análise das tecnologias que serão utilizadas no backend do projeto. O objetivo é entender as funcionalidades de cada tecnologia, suas vantagens e como elas se integram no desenvolvimento do sistema.

### Critérios de Aceitação

- [x] Documentação sobre como usar cada tecnologia e o que é importante para o backend.
- [x] Identificação de possíveis problemas ou limitações para cada tecnologia.
- [x] Análise de compatibilidade entre tecnologias.

### Escopo da Tarefa

- [x] Pesquisar e documentar o uso do **TypeScript** e **TSX** no backend.
- [x] Estudar o uso do **Vitest** para testes unitários.
- [x] Estudar o uso do **Jest** e do **Supertest** para testes de integração.
- [x] Estudar o uso do **Cypress** para testes end-to-end.
- [x] Entender como configurar e usar **Express** com **CORS** para criação de APIs REST.
- [x] Explorar o **PrismaORM** para modelagem e manipulação de dados.
- [x] Configurar **Dotenv** para gerenciar variáveis de ambiente de forma segura.
- [x] Entender o uso do **Zod** para validação de dados.
- [x] Entender como o **Jsonwebtoken** funciona para a autenticação e autorização via token.
- [x] Entender como usar o **Winston** para registro de logs no backend.
- [x] Estudar o **Bcrypt** para hashing seguro de senhas.

### Técnicas e Ferramentas Necessárias

- TypeScript
- TSX
- Vitest
- Jest
- Supertest
- Cypress
- Express
- CORS
- PrismaORM
- Dotenv
- Zod
- Jsonwebtoken
- Winston
- Bcrypt

**Comment by LucasAlves71** [comment]
Issue completed!
The content is available on https:https://github.com/unb-mds/2024-2-Squad11/blob/main/documents/doc-backend.md
